---
name: nats

addons:
- name: bpm
  include:
    stemcell:
    - os: ubuntu-trusty
  jobs:
  - name: bpm
    release: bpm

releases:
- name: bpm
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.1
  version: 1.1.1
  sha1: a7ea57aaf44a8217bae2a3df72a1afc51334e930
- name: nats
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest
update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
- name: nats-server
  azs: [z1, z2, z3]
  instances: 3
  jobs:
  - name: nats
    release: nats
    properties:
      nats:
        user: nats
        password: "((nats_password))"
  networks:
  - name: default
  vm_type: default
  stemcell: default
- name: nats-smoke-tests
  azs: [z1]
  vm_type: default
  stemcell: default
  instances: 1
  lifecycle: errand
  jobs:
  - name: smoke-tests
    release: nats
  networks:
  - name: default

variables:
- name: nats_password
  type: password
