#!/bin/bash -exu

# Not able to resolve our import via shellcheck, so disable warning
# shellcheck disable=SC1091
source networking-oss-deployments/scripts/script_helpers.sh

function check_input_params() {
  if [ -z "$DEPLOYMENT_NAME" ]; then
    echo "DEPLOYMENT_NAME has not been set"
    exit 1
  fi
  if [ -z "$ERRAND_NAME" ]; then
    echo "ERRAND_NAME has not been set"
    exit 1
  fi
}

function main() {
  check_input_params
  bosh_login_toolsmiths

  bosh -d "${DEPLOYMENT_NAME}" run-errand "${ERRAND_NAME}"
}

main
