#!/bin/bash -x

BASEDIR="$(cd $(dirname "$0") && pwd)"
RELEASE_DIR="${BASEDIR}/.."

IMAGE="cloudfoundry/cf-routing-pipeline"
MOUNT_DIR="/nats-release"
RUN_TESTS="cd ${MOUNT_DIR}; source .envrc; scripts/run_integration_tests" 

docker pull "${IMAGE}"
docker run -it \
  -v "${RELEASE_DIR}:${MOUNT_DIR}" \
  "${IMAGE}" \
  /bin/bash 
