#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

docker run \
  -it \
  --mount type=bind,source="${DIR}/..",target=/nats-release \
  ruby:3 \
  "/nats-release/scripts/run_job_property_tests"
