#!/bin/bash

set -eu

THIS_FILE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

"${THIS_FILE_DIR}/docker/container.bash" -d

docker exec nats-release-docker-container '/repo/scripts/docker/tests-templates.bash'
docker exec nats-release-docker-container '/repo/scripts/docker/test.bash' "$@"
docker exec nats-release-docker-container '/repo/scripts/docker/lint.bash'
