name: GitHub Actions
on:
  pull_request:
    branches:
      - develop
jobs:
  template-tests:
    runs-on: ubuntu-latest
    container: cloudfoundry/tas-runtime-build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: template-tests
        run: |
          bundle install
          bundle exec rspec spec
